#!/usr/bin/env python3
"""Check this repository's copied files against the repository that owns them.

    check-copies.py [--crt PATH] [--list]

Several files here are copies. They are not generated, not included from
elsewhere at build time, and nothing at build time notices when they go stale —
a drifted linker config produces a cartridge that links, boots, and reads the
wrong bank. This compares each copy with its original and says which moved.

    6502-128K.cfg       6502-CRT, generated by its tools/make-cart-cfg.mjs
    6502-256K.cfg       ("make configs" there; "make check-configs" fails on a
    6502-512K.cfg        stale one, which is the check upstream of this one)
    6502-1M.cfg

    6502.inc            6502-CRT, but only as a peer: these two have no
    6502-VDP.inc        generator and no owning repository. 6502-ASM, 6502-CRT
                        and 6502-C hold the same bytes and a change is made in
                        all three. check-include.py is what checks their
                        CONTENTS against a BIOS build; this only checks that
                        the three copies still agree.

6502-16K.cfg is deliberately absent: it is this repository's own file. It says
in prose what 6502-CRT's 6502.cfg says in the same MEMORY block, and the two
are not byte-identical on purpose.

Prints one summary line and exits non-zero on any difference.
"""

import argparse
import pathlib
import sys

# (file name, attribute of args holding the upstream checkout, why)
COPIES = [
    ("6502-128K.cfg", "crt", "generated"),
    ("6502-256K.cfg", "crt", "generated"),
    ("6502-512K.cfg", "crt", "generated"),
    ("6502-1M.cfg", "crt", "generated"),
    ("6502.inc", "crt", "peer"),
    ("6502-VDP.inc", "crt", "peer"),
]

HERE = pathlib.Path(__file__).resolve().parent.parent


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--crt", default=str(HERE.parent / "6502-CRT"),
                    help="a 6502-CRT checkout (default: ../6502-CRT)")
    ap.add_argument("--list", action="store_true", help="list the copies and exit")
    args = ap.parse_args()

    if args.list:
        for name, repo, why in COPIES:
            print(f"{name}\t{getattr(args, repo)}\t{why}")
        return 0

    same = []
    problems = []
    for name, repo, why in COPIES:
        mine = HERE / name
        theirs = pathlib.Path(getattr(args, repo)) / name
        if not mine.exists():
            problems.append(f"{name}: missing here")
        elif not theirs.exists():
            problems.append(f"{name}: no original at {theirs}")
        elif mine.read_bytes() != theirs.read_bytes():
            problems.append(f"{name}: differs from {theirs} ({why}) — "
                            f"here {mine.stat().st_size}, there {theirs.stat().st_size} bytes")
        else:
            same.append(name)

    for p in problems:
        print(p)
    print(f"{len(same)} match, {len(problems)} differ")
    return 1 if problems else 0


if __name__ == "__main__":
    sys.exit(main())
